AM_Nihoul_website/admin/views.py
import bs4
import flask
from flask import Blueprint, jsonify, current_app
from flask.views import MethodView
import flask_login
from flask_login import login_required
from flask_uploads import UploadNotAllowed
from PIL import Image
from bs4 import BeautifulSoup

from sqlalchemy import func

from werkzeug.datastructures import FileStorage

import base64
import io
from datetime import datetime
import re
import subprocess

import AM_Nihoul_website
from AM_Nihoul_website import db, User, limiter, pictures_set
from AM_Nihoul_website.admin.utils import Thumbnailer
from AM_Nihoul_website.base_views import FormView, BaseMixin, RenderTemplateView, ObjectManagementMixin, \
    DeleteObjectView
from AM_Nihoul_website.admin.forms import LoginForm, PageEditForm, CategoryEditForm, UploadForm, NewsletterEditForm, \
    NewsletterPublishForm, MenuEditForm, AlbumEditForm, PictureUploadForm, BriefEditForm, \
    FeaturedEditForm
from AM_Nihoul_website.visitor.models import Page, Category, UploadedFile, NewsletterRecipient, Newsletter, Email, \
    MenuEntry, EmailImageAttachment, Album, Picture, MenuType, Brief, Featured

admin_blueprint = Blueprint('admin', __name__, url_prefix='/admin')


class LoginView(BaseMixin, FormView):
    form_class = LoginForm
    template_name = 'admin/login.html'
    decorators = [limiter.limit(AM_Nihoul_website.LOGIN_LIMIT)]

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['next'] = flask.request.args.get('next', '')
        return ctx

    def dispatch_request(self, *args, **kwargs):

        if flask_login.current_user.is_authenticated:
            flask.flash('Vous êtes déjà connecté', category='error')
            return flask.redirect(flask.request.args.get('next', flask.url_for('visitor.index')))

        return super().dispatch_request(*args, **kwargs)

    def form_valid(self, form):

        if form.login.data != current_app.config['USERNAME'] or form.password.data != current_app.config['PASSWORD']:
            flask.flash('Utilisateur ou mot de passe incorrect', 'error')
            return self.form_invalid(form)

        flask_login.login_user(User(form.login.data))

        next = form.next.data
        self.success_url = flask.url_for('admin.index') if next == '' else next
        return super().form_valid(form)


admin_blueprint.add_url_rule('/login.html', view_func=LoginView.as_view(name='login'))


@login_required
@admin_blueprint.route('/logout', endpoint='logout')
def logout():
    flask_login.logout_user()
    flask.flash('Vous êtes déconnecté.')
    return flask.redirect(flask.url_for('visitor.index'))


# -- Index
class AdminBaseMixin(BaseMixin):
    decorators = [login_required]


class IndexView(AdminBaseMixin, RenderTemplateView):
    template_name = 'admin/index.html'
    decorators = [login_required]

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['content'] = db.session.get(Page, current_app.config['PAGES']['admin_index'])

        # few statistics
        sz_uploads = UploadedFile.query\
            .with_entities(func.sum(UploadedFile.file_size).label('total'))\
            .first()
        sz_pictures = Picture.query\
            .with_entities(func.sum(Picture.picture_size).label('total'))\
            .first()

        # bot service?
        bot_service_status = 'non configuré'
        if current_app.config['BOT_SERVICE_NAME'] is not None:
            cmd = '/usr/bin/systemctl is-active {}'.format(current_app.config['BOT_SERVICE_NAME'])
            status = subprocess.call(cmd, shell=True, executable='/bin/bash')
            bot_service_status = 'actif' if status == 0 else 'inactif (code={})'.format(status)

        ctx['statistics'] = {
            "Nombre d'inscrits à l'infolettre": NewsletterRecipient.query.count(),
            "Nombre d'infolettres": '{} (dont {} publiées)'.format(
                Newsletter.query.count(), Newsletter.query.filter(Newsletter.draft.is_(False)).count()),
            'Statut service infolettre': '{}'.format(bot_service_status),
            'Nombre de pages': Page.query.count(),
            'Taille des fichiers': '{:.2f} Mio'.format(
                sz_uploads[0] / 1024 / 1024 if sz_uploads[0] is not None else 0),
            'Taille des photos': '{:.2f} Mio'.format(
                sz_pictures[0] / 1024 / 1024 if sz_pictures[0] is not None else 0)
        }

        return ctx


admin_blueprint.add_url_rule('/index.html', view_func=IndexView.as_view(name='index'))


# -- Pages
class PagesView(AdminBaseMixin, RenderTemplateView):
    template_name = 'admin/pages.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        # fetch list of pages
        ctx['pages'] = Page.query.order_by(Page.slug).all()
        ctx['categories'] = Category.ordered_items().all()
        ctx['categories'].append(None)

        return ctx


admin_blueprint.add_url_rule('/pages.html', view_func=PagesView.as_view(name='pages'))


class BasePageEditView(AdminBaseMixin, FormView):
    form_class = PageEditForm
    template_name = 'admin/page-edit.html'

    def get_form(self):
        form = super().get_form()

        # add choices for categories
        categories = Category.ordered_items().all()

        choices = [(-1, '** pas de catégorie **')]
        choices.extend((c.id, c.name) for c in categories)
        form.category.choices = choices

        # add choices for next
        choices = {}
        q = Page.query.order_by(Page.title)

        if isinstance(self, PageEditView):  # avoid getting the page looping to itself
            q = q.filter(Page.id.isnot(self.object.id))

        pages = q.all()

        choices['No category'] = [(-1, '** pas de page suivante **')]
        choices['No category'].extend((p.id, p.title) for p in pages if p.category_id is None)

        for category in categories:
            choices[category.name] = [(p.id, p.title) for p in pages if p.category_id == category.id]

        form.next.choices = choices

        return form


class PageEditView(ObjectManagementMixin, BasePageEditView):
    model = Page

    def get_object_or_abort(self, *args, **kwargs):
        """Add slug check"""

        super().get_object_or_abort(*args, **kwargs)

        if self.object.slug != kwargs.get('slug', None):
            flask.abort(404)

    def get(self, *args, **kwargs):
        self.get_object_or_abort(*args, **kwargs)
        return super().get(*args, **kwargs)

    def post(self, *args, **kwargs):
        self.get_object_or_abort(*args, **kwargs)
        return super().post(*args, **kwargs)

    def get_form_kwargs(self):
        return {
            'title': self.object.title,
            'content': self.object.content,
            'category': -1 if self.object.category_id is None else self.object.category_id,
            'next': -1 if self.object.next_id is None else self.object.next_id
        }

    def form_valid(self, form):
        self.object.title = form.title.data
        self.object.content = form.content.data
        self.object.category_id = form.category.data if form.category.data >= 0 else None
        self.object.next_id = form.next.data if form.next.data >= 0 else None

        db.session.add(self.object)
        db.session.commit()

        flask.flash('Page "{}" modifiée.'.format(self.object.title))

        self.success_url = flask.url_for('visitor.page-view', id=self.object.id, slug=self.object.slug)
        return super().form_valid(form)


admin_blueprint.add_url_rule(
    '/page-edition-<int:id>-<string:slug>.html', view_func=PageEditView.as_view(name='page-edit'))


class PageCreateView(BasePageEditView):

    def form_valid(self, form):
        page = Page.create(form.title.data, form.content.data)

        if form.category.data >= 0:
            page.category_id = form.category.data

        if form.next.data >= 0:
            page.next_id = form.next.data

        db.session.add(page)
        db.session.commit()

        flask.flash('Page "{}" créée.'.format(page.title))

        self.success_url = flask.url_for('admin.pages')
        return super().form_valid(form)


admin_blueprint.add_url_rule('/page-nouveau.html', view_func=PageCreateView.as_view(name='page-create'))


class PageDeleteView(AdminBaseMixin, DeleteObjectView):
    model = Page

    def pre_deletion(self, obj):
        if obj.protected:
            return False

        return True

    def post_deletion(self, obj):
        self.success_url = flask.url_for('admin.pages')
        flask.flash('Page "{}" supprimée.'.format(obj.title))


admin_blueprint.add_url_rule('/page-suppression-<int:id>.html', view_func=PageDeleteView.as_view('page-delete'))


class BaseToggleVisibility(AdminBaseMixin, ObjectManagementMixin, MethodView):
    methods = ['GET']
    redirect_url = ''

    def get(self, *args, **kwargs):
        self.get_object_or_abort(*args, **kwargs)
        self.object.visible = not self.object.visible

        db.session.add(self.object)
        db.session.commit()

        return flask.redirect(flask.url_for(self.redirect_url))


class PageToggleVisibility(BaseToggleVisibility):
    model = Page
    redirect_url = 'admin.pages'


admin_blueprint.add_url_rule(
    '/page-visible-<int:id>.html', view_func=PageToggleVisibility.as_view('page-toggle-visibility'))


# -- Categories
class CategoriesView(AdminBaseMixin, FormView):
    template_name = 'admin/categories.html'

    form_class = CategoryEditForm

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        # fetch list of category
        ctx['categories'] = Category.ordered_items()
        return ctx

    def form_valid(self, form):
        if form.is_create.data:
            c = Category.create(form.name.data)
            flask.flash('Catégorie "{}" créée.'.format(c.name))
        else:

AM_Nihoul_website/templates/album.html
{% extends "base.ex.html" %}

{% block page_title %}{{ album.title }}{% endblock %}

{% block og_description %}Un album photo de l'{{ site_name }}{% endblock %}
{% block og_type %}article{% endblock %}
{% block og_image %}{% if album.thumbnail %}{{ album.thumbnail.url() }}{% else %}{{ super() }}{% endif %}{% endblock %}
{% block og_image_alt %}{% if album.thumbnail %}La miniature de l'album{% else %}{{ super() }}{% endif %}{% endblock %}

{% block extra_meta %}
    <meta property="og:article:published_time" content="{{ album.date_created }}" />
    <meta property="og:article:modified_time" content="{{ album.date_modified }}" />
{% endblock %}

{% block section_content %}
        <p class="page-info">
            {% if current_user.is_authenticated %}
                Dernière modification <b>{{ album.date_modified|date_formatter }}</b>.
                <a href="{{ url_for('admin.album', id=album.id) }}">Éditer cet album</a>.
            {% endif %}
            <a href="{{ url_for('visitor.albums') }}">Retour à la liste des albums photo</a>.
        </p>

    {{ album.description|safe }}
    <div class="row" id="lightgallery">
        {% for picture in pictures %}
            <a
                    href="{{ picture.url() }}"
                    class="container col-md-6 col-lg-4 my-4"
                    data-pinterest-text="Pin it1"
                    data-tweet-text="{{ album.title }}"
            >
            <img src="{{ picture.url_thumb() }}" alt="{{ album.title }}" style="max-height:300px;" />
            </a>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/lightgallery.min.js" integrity="sha512-FDbnUqS6P7md6VfBoH57otIQB3rwZKvvs/kQ080nmpK876/q4rycGB0KZ/yzlNIDuNc+ybpu0HV3ePdUYfT5cA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/plugins/share/lg-share.min.js" integrity="sha512-yEGrATBiy50yeZFbev13bZClHPp0J54MtYtgfLBpICRjx+7N+jw09DLOEYmZ6dotLTXFyhw1aEcJ5UwV4ihS9Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/plugins/hash/lg-hash.min.js" integrity="sha512-VboI13y+zwFtpuJYWQ5PRlQ+9T9lFOaFucE+ibB+TrQPsSHICv8uXDJ/PxyP6dtlZCDfl1SFNmj0I1FSAkWyBg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/plugins/autoplay/lg-autoplay.min.js" integrity="sha512-4SHz3kWC669ys+fIc9+bO9wkOTkg599KEwF5HN0tnanOqGVeqdcLQWDkCPUUSMoxb+4Wy88yd4ozNsSL9nhYdg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
    lightGallery(document.getElementById('lightgallery'), {
        plugins: [lgShare, lgHash, lgAutoplay]
    });
</script>

{% endblock %}

{% block other_head_stuffs %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/css/lightgallery.min.css" integrity="sha512-Szyqrwc8kFyWMllOpTgYCMaNNm/Kl8Fz0jJoksPZAWUqhE60VRHiLLJVcIQKi+bOMffjvrPCxtwfL+/3NPh/ag==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/css/lg-share.min.css" integrity="sha512-dOqsuo1HGMv5ohBl/0OIUVzkwFLF8ZmjhpZp2VT2mpH5UuOJXwtBhxxtbrrEIpvTDWm7mESg0JsEl4zkUGv/gw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.5.0/css/lg-autoplay.min.css" integrity="sha512-LlHSkMTvyRwh1YjzXwk6bxjdt3huGhCyK1vlCC6f7Db/g+2sYXz2YNasyZHnMUgykqPksmD/44DIINhqpWBjig==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

AM_Nihoul_website/templates/albums.html
{% extends "base.ex.html" %}

{% block page_title %}Albums photo{% endblock %}


{% block section_content %}
    <p>Retrouvez ici les photos de nos différentes activités.</p>
    <div id="album-list">
        {% for album in albums %}

        <div class="album">
            <h3>{{ album.title }}</h3>

            <div class="row">
                {% for im in album.ordered_pictures()[:3] %}
                    <div class="col-md-3 col-sm-6 mb-4">
                        <a href="{{ url_for('visitor.album', id=album.id, slug=album.slug) }}#lg=1&slide={{ loop.index - 1 }}">
                        <img class="mr-3 im" src="{{ im.url_thumb() }}" alt="{{ album.title }}" width="100%" />
                            </a>
                    </div>

                    {% endfor %}

                 <div class="col-md-3 col-sm-6 mb-4">
                     <a href="{{ url_for('visitor.album', id=album.id, slug=album.slug) }}" class="im more">...</a>
                 </div>
            </div>


                {{ album.description|safe }}

                <p><a href="{{ url_for('visitor.album', id=album.id, slug=album.slug) }}" class="goto-album">Voir cet album</a></p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

AM_Nihoul_website/templates/base.ex.html
{% from 'bootstrap4/utils.html' import render_messages %}
{% from 'bootstrap4/form.html' import render_form_row %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block page_title %}{% endblock %} - {{ site_name }}</title>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0">
    <meta name="description" content="{{ site_description }}">
    <meta name="keywords" content="{{ site_keywords }}">

    <!-- facebook og / twitter card -->
    <meta property="og:type" content="{% block og_type %}website{% endblock %}" />
    <meta property="og:title" content="{% block og_title %}{{ self.page_title() }}{% endblock %}" />
    <meta property="og:description" content="{% block og_description %}{{ site_description }}{% endblock %}" />
    <meta property="og:image" content="{% block og_image %}{{ url_for('static', filename='images/facebook_placeholder.jpg', _external=True) }}{% endblock %}" />
    <meta property="og:image:alt" content="{% block og_image_alt %}Le logo de l'association{% endblock %}" />

    <meta name="twitter:card" content="{{ self.og_type() }}" />
    <meta name="twitter:title" content="{{ self.og_title() }}" />
    <meta name="twitter:description" content="{{ self.og_description() }}" />
    <meta name="twitter:image" content="{{ self.og_image() }}" />
    <meta name="twitter:image:alt" content="{{ self.og_image_alt() }}" />

    {% block extra_meta %}{% endblock %}

    {{ bootstrap.load_css() }}
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
    {% block other_head_stuffs %}{% endblock %}
    <link href="{{ url_for('static', filename='images/favicon.png') }}" rel="icon">
</head>

<body>
    {% if gtag != '' %}
    <div id="cookies-eu-banner" class="jumbotron-fluid" style="display: none;">
        <div class="container pb-3 pt-3">
            Autorisez-vous <a href="https://policies.google.com/privacy?hl=fr-BE">Google Analytics</a> à recueillir des données à des fins statistiques, via des cookies ?
            <a href="{{ cookies_explain_page }}" id="cookies-eu-more">Plus d'infos ici</a>.
            <span class="buttons ml-3">
            <button id="cookies-eu-reject">Rejeter</button>
            <button id="cookies-eu-accept">Accepter</button></span>
        </div>
    </div>
    {% endif %}

    <header>
        <ul class="nav justify-content-end container">
        {% for i in secondary_menu %}
            <li class="nav-item"><a href="{{ i.url }}" class="nav-link">{{ i.text }}</a></li>
        {% endfor %}
        </ul>
    </header>

    <nav class="navbar navbar-light bg-light navbar-expand-md">
        <div class="container">
            <a href="/" class="navbar-brand" ><img src="{{ url_for('static', filename='images/logo.svg') }}" alt="logo"> <!--<span class="d-none d-lg-inline">{{ site_name }}</span>--></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% for i in main_menu %}
                        <li class="nav-item"><a class="nav-link" href="{{ i.url }}">{{ i.text }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" id="messages-zone">
        {{ render_messages() }}
    </div>

    <div id="page-content">

        {% block page_content %}
            <div id="content" class="container mt-4 pb-4">
            {% block content %}
                <section>
                    <h2>{{ self.page_title() }}</h2>
                    {% block section_content %}{% endblock %}
                </section>
            {% endblock %}
            </div>

            {% include "newsletter.inc.html" %}
        {% endblock %}
    </div>

    <footer class="container mt-4">
        <div class="row">
            <div id="bottom-nav" class="col-lg-8 col-md-6 col-12">
                <div class="row">
                {% for k, pages in bottom_menu.items() %}
                    <div class="bottom-nav-block col-xl-4 col-lg-6 col-12">
                    <h3>{{ k }}</h3>
                        <ul>
                        {% for p in pages %}
                            <li><a href="{{ url_for('visitor.page-view', id=p.id, slug=p.slug) }}">{{ p.title }}</a></li>
                        {% endfor %}
                        </ul>
                    </div>

                {% endfor %}
                </div>
            </div>
            <div id="contact-info" class="col-lg-4 col-md-6 col-12">
                {{ contact_page.content|safe }}
            </div>
        </div>


        <div id="bottom-txt" class="mt-4 mb-4 pt-4">
            &copy; {{ site_name }}
            &bull; Site web par <a href="{{ author_url }}">{{ author_name }}</a>  (version: <a href="{{ repo_url }}/tree/v{{ site_version }}">{{ site_version }}</a>)
            {# admin #}
            {% if not current_user.is_authenticated %}
                &bull; <a href="{{ url_for('admin.login') }}">Sésame</a>
            {% else %}
                &bull; <a href="{{ url_for('admin.index') }}">Administration</a> (<a href="{{ url_for('admin.logout') }}">Se déconnecter</a>)
            {% endif %}
        </div>
    </footer>

    {% block scripts %}
        <script src="{{ url_for('static', filename='scripts.min.js') }}"></script>
        {{ bootstrap.load_js() }}
        {# add FontAwesome kit if available #}
        {% if fa_kit != '' %}
            <script src="https://kit.fontawesome.com/{{ fa_kit }}.js"></script>
        {% endif %}
        {% if gtag != '' and not no_tracking %}
            <script src="https://cdn.jsdelivr.net/npm/cookies-eu-banner@2.0.1/dist/cookies-eu-banner.min.js"></script>
            <script>
                new CookiesEuBanner(function () {
                    (function (w,d,s,g,i) {
                        /* add <script> */
                        let a = d.createElement(s);
                        a.async = true;
                        a.src = g + '?id=' + i;
                        let p = d.getElementsByTagName(s)[0];
                        p.parentNode.insertBefore(a, p);
                        /* create data layer */
                        w.dataLayer = w.dataLayer || [];
                        /* configure */
                        function gtag(){dataLayer.push(arguments);}
                        gtag('js', new Date());
                        gtag('config', i);
                    })(window, document, 'script', 'https://www.googletagmanager.com/gtag/js', '{{ gtag }}');
                }, true);
            </script>
        {% endif %}
        {% if recaptcha_public_key != '' and not no_tracking %}
            <script src="https://www.google.com/recaptcha/api.js"></script>
            <script>
                function recaptcha_submit(token) {
                    let form = document.getElementById('newsletter-form');
                    form.submit();
                }
            </script>
        {% endif %}
    {% endblock %}
</body>
</html>

AM_Nihoul_website/templates/brief.html
{% extends "base.ex.html" %}

{% block page_title %}{{ brief.title }}{% endblock %}
{% block og_description %}{{ brief.summary }}{% endblock %}
{% block og_type %}article{% endblock %}
{% block extra_meta %}
    <meta property="og:article:published_time" content="{{ brief.date_created }}" />
    <meta property="og:article:modified_time" content="{{ brief.date_modified }}" />
{% endblock %}

{% block content %}
    <section>
    <h2>{{ brief.title }}</h2>

        <p class="page-info">
            Créée {{ brief.date_created|date_formatter }}{% if brief.date_created < brief.date_modified %} (dernière modification <b>{{ brief.date_modified|date_formatter }}</b>){% endif %}.

            {% if not brief.visible %}<b>Cette brève n'est pas publique.</b>{% endif %}

            {% if current_user.is_authenticated %}
                <a href="{{ url_for('admin.brief-edit', id=brief.id, slug=brief.slug) }}">Éditer cette brève</a>.
                <a href="{{ url_for('admin.briefs') }}">Retour à la liste des brèves</a>.
            {% else %}
                <a href="{{ url_for('visitor.briefs') }}">Retour à la liste des brèves</a>.
            {% endif %}
        </p>

        {{ brief.content_with_summary()|safe }}
    </section>
        <section class="page-next">
        <p>
            <span class="fas fa-arrow-right"></span>
            {% if next_brief %}
                Brève suivante : <a href="{{ url_for('visitor.brief-view', id=next_brief.id, slug=next_brief.slug) }}">{{ next_brief.title }}</a>
            {% else %}
                <a href="{{ url_for('visitor.briefs') }}">Retour à la liste des brèves</a>
            {% endif %}
        </p>
        </section>
{% endblock %}

AM_Nihoul_website/templates/briefs.html
{% extends "base.ex.html" %}

{% block page_title %}Brèves{% endblock %}


{% block section_content %}

    <table class="admin-list">
        {% for brief in briefs %}
            <tr>
                <td class="left">
                    <span class="title"><a href="{{ url_for('visitor.brief-view', id=brief.id, slug=brief.slug) }}">{{ brief.title }}</a></span>
                    <span class="info">{{ brief.summary }} &bull; Publication {{ brief.date_created|date_formatter }}.</span>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

AM_Nihoul_website/templates/index.html
{% extends "base.ex.html" %}

{% block page_title %}Accueil{% endblock %}

{% block page_content %}
    <div id="index-page">
    <div id="index-head-jumbotron" class="jumbotron jumbotron-fluid pt-4 pb-4">
        <div class="container">
        <h1>{{ content.title }}</h1>
        {{ content.content|safe }}
        </div>
    </div>

    <div id="index-featured" class="pb-4">

        <h1>Mis en avant</h1>

        <div class="container">
        <div class="card-deck">

        {% for featured in featureds %}
            <div class="card{% if loop.last %} d-none d-xl-block{% elif loop.index == 3 %} d-none d-lg-block{% endif %}">
                <img class="card-img-top" src="{{ featured.image_link }}" alt="Card image cap">
                <div class="card-body">
                <h3 class="card-title">{{ featured.title }}</h3>
                <p class="card-text">{{ featured.text|safe }}</p>
                    <a href="{{ featured.link }}" class="btn btn-primary">{{ featured.link_text }}</a>
                </div>
            </div>
        {% endfor %}
         </div>
        </div>

    </div> <!-- featured -->
    
    {% include 'newsletter.inc.html' %}

    {% if latest_info|length > 0 %}

        <div id="index-briefs" class="pb-4">

        <h1>Nos dernières infos</h1>

        <div class="container">
        <div class="card-deck">

        {% for info in latest_info %}
            <div class="card{% if loop.last %} d-none d-lg-block{% endif %}">
                <div class="card-body">
                <h3 class="card-title">{{ info.title }}</h3>
                    <p class="text-muted">{{ info.type }} &bull; Publiée {{ info.date|date_formatter }}.</p>
                <p class="card-text">{{ info.summary }}</p>
                    <a href="{{ info.link }}" class="card-link">Lire la suite</a>
                </div>
            </div>
        {% endfor %}
         </div>
        </div>

        <div id="list-links" class="container mt-4 mb-4">
            <a href="{{ url_for('visitor.briefs') }}">Toutes nos brèves</a>
            &bull; <a href="{{ url_for('visitor.newsletters') }}">Toutes nos infolettres</a>
            &bull; <a href="{{ url_for('visitor.albums') }}">Toutes nos photos</a>
        </div>

        </div> <!-- briefs -->
    {% endif %}
    </div> <!-- index page -->
{% endblock %}

AM_Nihoul_website/templates/newsletter-in.html
{% extends "base.ex.html" %}
{% from 'bootstrap4/form.html' import render_field%}
{% set no_newsletter = True %}

{% block page_title %}Inscription à nos infolettres{% endblock %}


{% block section_content %}
        <form action="{{ url_for('visitor.newsletter-subscribe') }}" method="post" id="newsletter-form">
            {{ form.hidden_tag() }}
            {{ render_field(form.name) }}
            {{ render_field(form.email) }}
            {% if recaptcha_public_key != '' and not no_tracking %}
                    <button id="submit_button" name="submit_button" class="btn btn-primary mb-2 g-recaptcha"
                            data-sitekey="{{ recaptcha_public_key }}"
                            data-action="submit"
                            data-callback="recaptcha_submit">
                        S'inscrire</button>
            {% else %}
                <div class="col-md-2">{{ newsletter_form.submit_button(class_='btn btn-primary mb-2') }}</div>
            {% endif %}
        </form>
{% endblock %}

AM_Nihoul_website/templates/newsletter-out.html
{% extends "base.ex.html" %}
{% from "helpers.inc.html" import render_field %}
{% set no_newsletter = True %}

{% block page_title %}Désinscription de nos infolettres{% endblock %}


{% block section_content %}
        <p>Vous êtes désormais désinscrit de nos infolettres.</p>
{% endblock %}